name: PR and branch naming rule checker

on:
  pull_request:
    branches: [ master ]
    types: [ opened, edited, synchronize, reopened ]

jobs:
  naming_rule:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.set_output.outputs.status }}
    steps:

      - name: PR title checker
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^(((feature|hotfix|fix)\/){1}(((NINJAMA|ninjama|NINJAFE|ninjafe){1}-[0-9]{1,}.{1,}))|((nonjira|NONJIRA){1}-.{1,}))|^((version|release)\/){1}(((v|V){1}[0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}_.{1,}))$'
          github_token: ${{ secrets.TOKEN }}

      - name: PR title checker
        uses: deepakputhraya/action-branch-name@master
        with:
          regex: '^(((feature|hotfix|fix)\/){1}(((NINJAMA|ninjama|NINJAFE|ninjafe){1}-[0-9]{1,}.{1,}))|((nonjira|NONJIRA){1}-.{1,}))|^((version|release)\/){1}(((v|V){1}[0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}_.{1,}))$'
          ignore: master

  notification:
    runs-on: ubuntu-latest
    if: always()
    needs:
     - naming_rule
    steps:
    - uses: actions/checkout@v2
    - name: Expose git commit data
      uses: rlespinasse/git-commit-data-action@v1.x

    - name: Slack Notification
      if: ${{ needs.naming_rule.outputs.status == 'success' }}
      uses: rtCamp/action-slack-notify@v2.0.2
      env:
        SLACK_CHANNEL: android
        SLACK_COLOR: '#008000'
        SLACK_MESSAGE: 'Test build created succesfully ${{ github.head_ref }} : ${{ needs.naming_rule.outputs.status }} - ${{ env.GIT_COMMIT_COMMITTER_EMAIL }}'
        SLACK_TITLE: 'PR and Branch naming rule checker'
        SLACK_USERNAME: bot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        
    - name: Slack Notification
      if: ${{ needs.naming_rule.outputs.status != 'success' }} 
      uses: rtCamp/action-slack-notify@v2.0.2
      env:
        SLACK_CHANNEL: android
        SLACK_COLOR: '#FF0000'
        SLACK_MESSAGE: 'Error with PR and branch naming rule ${{ github.head_ref }} : ${{ needs.naming_rule.outputs.status }} - ${{ env.GIT_COMMIT_COMMITTER_EMAIL }}'
        SLACK_TITLE: 'PR and Branch naming rule checker'
        SLACK_USERNAME: bot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
